helium/proto

Cargo.lock
build.rs

Paths for `build.rs` needed updating

Fix Rust Crate

---

src/blockchain_txn.proto
src/blockchain_txn_multi_payment_v1.proto
src/blockchain_txn_payment_v2.proto

Add proto definition for `blockchain_txn_payment_v2` with additional `payment` msg encapsulating payee details.

Add payment_v2 proto

---

.gitignore
src/blockchain_block_v1.proto

update block format for performance voting

---

.travis.yml

Adds basic Erlang builds to the build matrix

Erlang proto travis build

---

src/blockchain_txn.proto
src/blockchain_txn_price_oracle_v1.proto

This adds the price oracle message protobuf definition

Add price oracle protobuf definition

---

src/blockchain_state_channel_v1.proto

Reverts helium/proto#33
Apparently we have some records on-chain with credits in them.

Revert "Remove credits from sc proto"

---

src/blockchain_state_channel_v1.proto

Proto PR for https://github.com/helium/miner/pull/405

Add support for 868 channel mapping

---

src/blockchain_txn_routing_v1.proto
src/blockchain_txn_state_channel_close_v1.proto
src/blockchain_txn_state_channel_open_v1.proto
src/blockchain_txn_token_burn_v1.proto

proto PR of https://github.com/helium/blockchain-core/pull/492

add missing & necessary fee fields to various protos

---

src/blockchain_txn.proto
src/blockchain_txn_transfer_hotspot_v1.proto

Problem to solve: enable hotspot transfers between owners
Clubhouse: https://app.clubhouse.io/hlm/story/8742/transfer-ownership-transaction

Add transfer hotspot transaction

---

Cargo.lock
Cargo.toml
build.rs
rebar.config
src/lib.rs
src/service/router.proto
src/service/validator.proto

add conditional service support

---

src/blockchain_txn.proto
src/blockchain_txn_gen_validator_v1.proto
src/blockchain_txn_stake_validator_v1.proto
src/blockchain_txn_transfer_validator_stake_v1.proto
src/blockchain_txn_unstake_validator_v1.proto
src/blockchain_txn_validator_heartbeat_v1.proto

validators

---

src/blockchain_txn_stake_validator_v1.proto
src/blockchain_txn_transfer_validator_stake_v1.proto
src/blockchain_txn_unstake_validator_v1.proto

without descriptions, these don't serve any function.

remove staking nonces

---

src/blockchain_txn.proto
src/blockchain_txn_rewards_v2.proto

Problem to solve: We want to shrink the size of the rewards transaction
Solution: Create a v2 of rewards for use in blockchain-core and miner

Rewards v2

---

src/blockchain_txn.proto
src/blockchain_txn_assert_location_v2.proto

Opening this to gather suggestions about what actually goes in this txn. Noteworthy detail is that `gateway_signature` has been excluded from here.

Add assert loc v2 proto

---

src/service/gateway.proto

Apologies for the whitespace changes.. I have proto auto-fmt turned on

keep gateway service in one service

---

src/blockchain_txn_payment_v2.proto

Adds a unit64 memo field to payment-v2

Add memo field to payment-v2

---

src/blockchain_state_channel_v1.proto

This PR renames `AS923` to `AS923_1` and adds `AS923_[2..4]`.

Add AS923 sub-regions

---

src/blockchain_region_param_v1.proto
src/blockchain_txn_poc_receipts_v1.proto

Add regulatory region specific channel parameters

Add region param proto

---

build.rs
src/lib.rs

Also renames Client to RouterClient to make it clear what this is since both are "clients to router"

Expose service StateChannelClient

---

src/service/gateway.proto

remove is_overpaid rpc

---

src/service/gateway.proto

Revert "remove is_overpaid rpc"

---

src/blockchain_txn_transfer_hotspot_v2.proto

Add a gateway nonce as well for transfer v2 transaction.

Add gw nonce to transfer v2 proto

---

src/service/gateway.proto

Adds proto def for region params RPC

Region Params requirements

---

src/blockchain_txn_payment_v2.proto
test/payment_v2.spec.js
yarn.lock

Satisfies the proto change requirement for https://github.com/helium/blockchain-core/pull/1138 as outlined in https://github.com/helium/blockchain-core/issues/1060.

Add "max" payment field value to payment_v2

---

src/service/gateway.proto

This add gain field to region param streamed responses

add gw gain to region params

---

package.json
yarn.lock

Upgrading a few dependencies to try and resolve a few open PRs
* https://github.com/helium/proto/pull/138

Upgrading to some dependencies

---

package.json
test/token_redeem_v1.spec.js

includes support for token redeem txn

bump js version to 1.6.0

---

build.rs
src/service/transaction.proto

ensure that rust builds have access to the transaction.proto service definition

include txn proto in rust builds

---

src/lib.rs
src/service/local.proto
src/service/transaction.proto

optional parameters don't play nice everywhere we need them to so these all need to be "required" now

remove optional parameters

---

build.rs
src/entropy.proto
src/lib.rs
src/service/follower.proto
src/service/transaction.proto

Moves service protos to their own namespace for transaction and follower

Add entropy definition

---

build.rs
src/blockchain_txn_subnetwork_rewards_v1.proto

Either one of these is fine for me

Add subnetwork_rewards message

---

src/service/poc_lora.proto

Revert "switch signal to float"

---

src/service/poc_mobile.proto

Also, removes speed_share which is not very useful

Add speedtest_avg and speedtest_avg_validity

---

build.rs
src/lib.rs

we want to be able to deserialize config related messages for the cli

add config service proto

---

src/lib.rs
src/mapper.proto
src/service/poc_mobile.proto

Add an ingest report for mapper attach events.

Add mapper_attach_ingest report

---

src/mapper.proto

Made a mistake on the type for signature and pub_key.

Fix mapper proto

---

build.rs
src/reward_manifest.proto

Add reward manifest to build.rs

---

build-cpp.sh
src/service/iot_config.proto

minor nits that hung up the github's approval

fix CI nits

---

build-cpp.sh
build.rs
src/lib.rs
src/service/poc_iot.proto

Standardise around iot naming convention in place of lora
Linked PR: https://github.com/helium/oracles/pull/270

rename lora to iot

---

build-cpp.sh
build.rs
src/lib.rs
src/service/poc_lora.proto

Revert "rename lora to iot"

---

src/service/poc_lora.proto

Linked oracle pr: https://github.com/helium/oracles/pull/306

replace valid_poc with poc, include valid & invalid witnesses

---

src/service/iot_config.proto

* Routes dont include euis and devaddr range anymore
* Stream EUIs and ranges update for scale

Scale Routes

---

src/service/iot_config.proto
src/service/packet_router.proto

* netid uint32
* Add locked and active to route

Active / Locked route

---

src/service/packet_verifier.proto

Invalid sessions are not possible right now

Add valid_data_transfer_session to packet verifier

---

src/blockchain_poc_core_v1.proto

Revert "Attach hex_scale and reward_unit to poc witness and receipts"

---

build-cpp.sh
build.rs
src/lib.rs
src/price_report.proto

Summary
----
Adds support for price_report

Add support for price report

---

package.json
test/service/downlink.spec.js

includes a sanity test to verify that the services directory is getting picked up by the js compiler

bump js version to 2.0

---

.github/workflows/cpp.yml
.github/workflows/erlang.yml
.github/workflows/lint.yml
.github/workflows/node.yml

* Upgrade workflow cancel step

Fix cpp build to use apt for protoc

---

package.json

bump js version to 2.0.1

---

src/lib.rs
src/service/iot_config.proto
src/service/packet_verifier.proto
src/service/poc_lora.proto

Adds config service APIs required by iot verifier
Extends valid packet to include additional fields required for dc rewards on iot verifier

config service APIs and dc transfer related additions for iot verifier

---

src/lib.rs
src/region.proto

Adds an UNKNOWN region to allow for an unknown region request for a gateway

Add an "unknown" region

---

src/service/poc_mobile.proto

Adds message support for subscriber location sharing and subsequent rewards

subscriber rewards support

---

src/service/packet_verifier.proto
src/service/poc_mobile.proto

Revert "subscriber id in data transfer requests and events"

---

src/service/poc_mobile.proto

Add new message to receive heartbeats from wifi hotspots
Linked oracle pr: https://github.com/helium/oracles/pull/623

Add wifi_heartbeat_req_v1

---

src/service/poc_mobile.proto

And possibly an "unknown" variant?

Add enum nova_generic_wifi_outdoor

---

src/service/poc_lora.proto

oracle pr: https://github.com/helium/oracles/pull/709

add reciprocity related invalid reasons

---

src/service/poc_mobile.proto

https://github.com/helium/oracles/pull/789

Add Landtype to oracle_boosting_hex_assignment

---

src/service/poc_mobile.proto

This reverts https://github.com/helium/proto/pull/415

Revert Merge pull request #415

---

src/service/poc_mobile.proto

Revert "hip 118 visualization data "

---

beacon/src/region.rs
src/service/mobile_config.proto
src/service/poc_mobile.proto

Supports: https://github.com/helium/oracles/pull/984
Add hotspot banning rpc and messages for `poc_mobile` ingester.
What are some more applicable reasons for ` ban_reason`?

Hotspot Banning

---

src/service/packet_verifier.proto

See https://github.com/helium/oracles/pull/980

Add burn_timestamp to valid_data_transfer_session

---

src/service/mobile_config.proto

Related PR: https://github.com/helium/oracles/pull/1016. See description there

[Mobile Config] new gateway service grpc endpoint: info_stream_v3
