src/hotspot_protocol/longfi.proto

Updated the LongFi protobuf to reflect more closely the [longfi-core struct](https://github.com/helium/longfi-core/blob/lthiery/testing-with-longfi-device/include/lfc/datagram.h#L65)
If we can agree on this, than this unblocks [CH#5233](https://app.clubhouse.io/hlm/story/5233/update-router-for-new-protobuf-format)

update LongFi structure

---

src/hotspot_protocol/longfi.proto

Routers need the original golay-decoded tag bits to verify datagram fingerprints. This PR adds them in the most unobtrusive, if not pretty, way. 
Ideally, in a future PR, we'll make `LongFiRxPacket` contain a `one_of datagram`. It's not needed now though since we're only using `monolithic` datagrams.

Add datagram tag bits to RX packet message

---

src/blockchain_state_channel_v1.proto
src/blockchain_txn.proto
src/blockchain_txn_add_gateway_v1.proto
src/blockchain_txn_assert_location_v1.proto
src/blockchain_txn_coinbase_v1.proto
src/blockchain_txn_consensus_group_v1.proto
src/blockchain_txn_create_htlc_v1.proto
src/blockchain_txn_dc_coinbase_v1.proto
src/blockchain_txn_gen_gateway_v1.proto
src/blockchain_txn_oui_v1.proto
src/blockchain_txn_payment_v1.proto
src/blockchain_txn_poc_receipts_v1.proto
src/blockchain_txn_poc_request_v1.proto
src/blockchain_txn_redeem_htlc_v1.proto
src/blockchain_txn_rewards_v1.proto
src/blockchain_txn_routing_v1.proto
src/blockchain_txn_security_coinbase_v1.proto
src/blockchain_txn_security_exchange_v1.proto
src/blockchain_txn_state_channel_close_v1.proto
src/blockchain_txn_state_channel_open_v1.proto
src/blockchain_txn_token_burn_exchange_rate_v1.proto
src/blockchain_txn_token_burn_v1.proto
src/blockchain_txn_update_gateway_oui_v1.proto
src/blockchain_txn_vars_v1.proto
src/lib.rs
src/packet.proto

This flattens the namespace to just `helium` to avoid cross language issues with tools that don't support protobuf packages well

Flatten to helium namespace to avoid tool interactions

---

src/blockchain_txn_create_htlc_v1.proto

This adds a nonce to the `blockchain_txn_create_htlc_v1` txn type and is to enable absorbed/2 checks in blockchain core.  The related blockchain core PR is:
https://github.com/helium/blockchain-core/pull/305

add nonce to create_htlc txns

---

src/blockchain_txn_oui_v1.proto
src/blockchain_txn_state_channel_open_v1.proto
src/packet.proto

- `blockchain_txn_oui_v1` does not have an OUI field anymore
- `blockchain_txn_state_channel_open_v1` now has an OUI field
- `packet.proto` updated with routing information

More state channel related fixes

---

src/blockchain_state_channel_v1.proto
src/packet.proto

For some reason we lost the compatibility conversions in the proto merge, this should restore them.

Be more compatible with older message definitions

---

src/blockchain_state_channel_v1.proto

We can remove it once we fix snapshots to contain encoded blocks rather than decoded records.

Reinstate field 7 for snapshot compatability

---

src/service/gateway.proto

rename to avoid confusion with the wider validator project

rename validator service to gateway

---

src/blockchain_txn_gen_validator_v1.proto
src/blockchain_txn_stake_validator_v1.proto
src/blockchain_txn_transfer_validator_stake_v1.proto
src/blockchain_txn_unstake_validator_v1.proto
src/blockchain_txn_validator_heartbeat_v1.proto

Consistently name validator address `address`. Add an `amount` to stake_transfer which defines the number of bones the new owner will pay the old owner as part of absorbing this transaction

Fixups for validator transactions

---

src/blockchain_txn_stake_validator_v1.proto
src/blockchain_txn_transfer_validator_stake_v1.proto
src/blockchain_txn_validator_heartbeat_v1.proto

Validator signatures are present to indicate key ownership, and as such only safety feature.
For simplicity of stake/unstake/transfer flows, remove these validator signature fields.
Also fixes up heartbeat block height to have a uint64 type

No validator signatures

---

package.json
yarn.lock

addresses security vulnerability in versions of `node-notifier` prior to `8.0.1`

fix node notifier version

---

src/blockchain_txn_unstake_validator_v1.proto

Problem to solve: We want to make the stake release height explicit and agreed when an unstake txn is processed.
Addresses helium/miner#736

Add stake_release_height field to unstake txn

---

src/blockchain_region_param_v1.proto

We have never used the region proto on chain thus it's okay to modify the spreading proto here. We will use this version which has a `max_packet_size` tagged_spreading making it easier to lookup which spreading factor to use on the miner side.

Spreading with packet size

---

src/service/gateway.proto

Adds fields expiry_at_block and original_dc_amount
Linked PRs:
https://github.com/helium/sibyl/pull/13

add additional fields to is_active resp

---

src/blockchain_txn.proto
src/blockchain_txn_transfer_hotspot_v2.proto

proto for https://github.com/helium/blockchain-core/issues/978
Preparation for a much simpler version of hotspot transfer transaction containing only:
```
-  owner_signature
-  owner_address
-  gateway_address
-  new_owner_address
```

Add transfer_hotspot_v2 proto

---

src/lib.rs

prost::Message provides functions which return `Result<_, Encode/DecodeError>`. It's easy to derive application level errors from these errors if we make these types accessible to the client. Otherwise, the client needs to import the right version of `prost` themselves.

Rust: pub use prost::Encode/DecodeError

---

src/service/gateway.proto

This proposes that
1. we use blockchain_var_v1 as the encoding type for var key/value pairs. It's already used and includes the type of the value that is encoded in the binary
2. Only stream back keys of changed chain variables. The reasoning is that most chain var changes are not relevant to light gateways, and some (like maker keys or pocv11 region maps) are quite large. Streaming back unused values is not good for bandwidth. With this change the client would still get the keys of values that were changed but would have to come back to ask for the values.

config service updates

---

Cargo.toml
build.rs

Actually, by default, rustfmt is needed for all builds. As rustfmt is here only to prettify the generated proto files (very useful for debug), it can be removed for production builds.
I could not find a way to differentiate the build-dependency depending on the profile (dev, release).

Remove rustfmt in tonic-build dependency by default to allow production builds without rustfmt

---

src/service/gateway.proto

Adds a RPC to retrieve a random selection of validators.  The client can specify the quantity of random validators to return.  The data per validator includes pubkey and routing data.

add validators grpc req

---

src/lib.rs
src/service/local.proto

The dance between ConfigValue and BlockchainVarV1 is to work around my inability to use protos from the other package without causing issues

Add config local rpc request

---

src/service/local.proto

adds an `info` method to the local api service which exposes service specific information

Add info rpc to local api service

---

src/service/local.proto

The local grpc service needs to have an ecdh route added to implement a gateway-rs replacement for the ecc-worker

adding ecdh route to local grpc

---

src/service/local.proto

This exposes the gateway region as a local call. 
Since Prost/protoc still has issues importing across namespaces we leave the region encoded as i32 and have the client do the right thing :-/

expose region local call

---

src/service/local.proto

The current hotspots allow for (ebus) rpc communication with the miner to allow generating and returning a signed `blockchain_txn_add_gateway_v1` transaction so the rust light gateway will need to support this functionality as well. This rpc provides a bridge api between the legacy call (which accepts an owner, payer, amount, and fee) and the newer api currently defined in the light gateway where staking fees are immediately known based on the mode of the device and do not need to be calculated from the chain.

Extend local rpc api with add_gateway_txn

---

src/service/follower.proto

Required proto definition for https://github.com/helium/blockchain-node/pull/139. Defines the proto service for the blockchain-node follower to stream transaction information to consumers for off-chain activities.

Define follower service and req/resp

---

src/service/transaction.proto

fixes the enum order options following the removal of the `cleared` option and specifies the unary resp types since the transaction service currently doesn't have a generic response envelope.

fix enum order, specify resp msgs

---

src/blockchain_txn_handler.proto

This extends `blockchain_txn_info_v1` to include a field to track the negotiation dialler txn protocol between the txn mgr and a CG member.

add field to track dialed txn protocol version

---

src/blockchain_sync_handler.proto

Add flag to blockchain_sync record to indicate final batch of blocks

add final flag to sync blocks message

---

.github/workflows/rust.yml
src/service/follower.proto

having the height field in a follower stream join request is causing problems so we need to make the field required.

need to make follower request height mandatory

---

Cargo.toml
build.rs

protobuf-src appears to be broken on windows. The problem we're solving by using protobuf-src only applies to Linux, so let's use system protoc for Windows.

Do not use protobuf-src for Windows builds

---

src/service/follower.proto

in order to migrate the rewards off-chain servers away from consensus group block triggers, we need to be able to receive the last reward block height of the associated subnetwork in order to construct the subnetwork rewards txn (which requires a start epoch and end epoch block height values).
this change allows the blockchain node follower providing the follower grpc service to the reward server to query that from the chain synchronously when evaluating and preparing reward transaction.

adding last reward height grpc api

---

src/lib.rs

Questions:
- Is DecodeError implemented properly?
- An easier way to compare strings?
- Is the impl block scoped correctly?

implement FromStr for DataRate enum

---

src/service/follower.proto

allow pulling all currently active gateways from the source of truth on recently beaconed gateways asserted to the chain for validation (density calculations initially) by off-chain oracle

add streaming gateway info endpoint

---

src/entropy.proto
src/lib.rs

The version (default to 0) indicates how the entropy is intended to be decoded and used.
The current default version is 0. It indicates that the beacon payload is to be constructed using the sha256 of the remote entropy, remote entropy timestamp, and local entropy in that order.
This is implemented in the `entropy` workspace member of the gateway-rs repo

Add version to entropy

---

src/service/follower.proto

allow streaming active gateway results in batches instead of one at a time since there are hundreds of thousands of records at a given time

Allow batching of gw info results

---

build.rs
src/lib.rs
src/service/config.proto
src/service/packet_router.proto

This supersedes https://github.com/helium/proto/pull/157 which was too convoluted due to many `merge master`, etc.
Add:
- `package helium.config`
- `package helium.packet_router`

Add config, packet_router protos

---

src/service/poc_lora.proto

Add support for an error enum to cover beacon and witness reports which end up getting purged due to being stale.  This will be outputted with the invalid report by the verifier

add invalid enum to cover stale reports

---

src/service/follower.proto

pre-requisite to https://github.com/helium/blockchain-node/pull/181, allows the response from the blockchain-node to distinguish between a result with location and region information and when the ledger is unable to verify the gateway by the requested pubkey

push gateway not found lookup result to the app level

---

src/service/poc_mobile.proto

Current protobuf poc_mobile::share really represents a valid or invalid heartbeat so changing the name and removing the wrapper(shares).

Change poc_mobile share to heartbeat

---

README.md

When and why to use specific types and units for various values.
The initial commit is just a rough draft.

Guide for contributors

---

src/service/poc_mobile.proto

Based on a brief discussion with @meowshka, float seems like the most appropriate value for the multiplier.

Add reward multiplier to speedtest_avg

---

src/scaling_factors.proto

adds a message type for the off-chain oracle hex density scaling factor server to write out its results each interval to a reporting bucket for auditability

add scaling factor map proto

---

src/mapper.proto

This allows the ingester to add hotspots into message at a scope where it is not expected to be signed. This preserves the rule that mapper.message may always be verifeid without clearing any fields.

include hotspots at mapper.message

---

src/service/poc_lora.proto

within the application code, to avoid imprecise conversions for rewards we use the Decimal implementation defined in `rust_decimal`; the string format of the type when serialized over the wire is likely to lead to more precise interpretations of the intended value across different systems/architectures than converting to and from floating point types.

convert wire-format of scaling factor to string

---

src/scaling_factors.proto
src/service/poc_lora.proto

to avoid precision conflicts across architectures, represent these scaling factor percentages as integers; in practice they are a 2-decimal precision percentage multiplier.

convert scaling factors to integers

---

src/service/poc_lora.proto

necessary for moving the calculation of the reward unit (a multiplier of iot reward shares) currently encapsulated within the Iot Injector but being moved to the IoT Verifier. Rather than multiplying the `hex_scale` and `reward_unit` values within the verifier and sending the values as a single field in the outgoing valid reports for ease of upgrading the existing proto messages as well as additional transparency they are sent as separate fields.

add reward unit to beacon and witness reports

---

src/service/poc_lora.proto

the included new message type in the iot poc service mirrors the `radio_reward_shares` message type in the mobile verifier for aggregating all rewards accumulated by a given hotspot within a reward calculation period which can then be collected under a reward manifest for the given period and emitted to an iot reward indexer for issuing IoT subnetwork rewards to the hotspot as part of off-chain poc rewards.
the structure of the message is largely the same except the atomic unit of reward accumulation for the iot subnetwork is the lorawan gateway, whereas the mobile subnetwork's is the cbrs radio.

adding gateway reward shares message for iot subnetwork rewards

---

src/service/poc_lora.proto

This change is required as a pre-requisite to IoT PoC witness and beacon validation including returning a valid scaling factor as part of validation.

add missing scaling factor poc invalid reason

---

src/service/iot_config.proto

updated action enum values to be have the type
you can't have enums in a namespace with conflicting values.
`action_v1` has create/update/delete for streaming config information to subscribers, which means we can't use any of those words as enum values anywhere else.

add devaddr rpc for route

---

src/lib.rs

adding convenience re-exports to the iot_config service for the server-side api services

adding server-side reexports for iot_config service

---

src/lib.rs

didn't catch this until it was merged since the CI check doesn't run if your target isn't the master branch

fixing rust formatting

---

src/service/iot_config.proto

A "Helium" org would have 1-n ranges within the Helium NetID. "Roaming" orgs would have a single range that spans their entire NetID.
Any Routes created or updated will have their devaddr ranges checked against the orgs list of devaddr range restrictions.
In thinking about calling this field "restrictions", there could be more fields for an org that come along and "restrict" their ability to do various things. In other messages, devaddr_ranges are named the same, and the intent can be easily inferred through the context of the message.

add devaddr_ranges field to org_v1

---

src/service/iot_config.proto

Add a new service definition for light gateways to request the current region params for their asserted location. Post-activation of off-chain PoC this service/rpc will supersede the current service/rpcs in place against durable validators.
The requesting gateway will now only require to submit its address (with signature) and the config service will perform a lookup of the verified address's on-chain location before looking up and returning the region params for the location's region.

add gateway service with region param req/res to config service

---

build.rs
src/lib.rs

This update to the lib.rs and build.rs are needed to allow the generated code to properly import the struct type of the region params newly added to the iot_config service and to do deserialization of the type.

add missing region params message

---

src/service/poc_lora.proto

Adds general error to be used as the invalid reason for a witness or beacon should verification hit an unexpected error and no specific verification fail reason can be determined

support generic error as invalid reason

---

build.rs

implement deserialize alongside serialize for the core proto messages used throughout various projects to simplify and consolidate definitions of the commonly used protos into the proto repo and avoid having to re-implement them or else wrap them in new types to allow defining common traits like (de)serialize

derive deser for region (and others)

---

src/service/iot_config.proto

adds two IoT Config oracle service capabilities:
- enable adding delegate keys to a new org at the time of creation where previously adding delegate keys could only be done by updating a previously created org
- adds a `enable` rpc to the org service as a complement to the `disable` rpc

add org create delegate keys, enable org rpc

---

src/lib.rs
src/service/local.proto

* Add `GatewayClient` to the `iot_config` namespace for consistent access
* Remove `StateChannelClient` from `router` since it’s no longer used
* Remove the BlockchainVarV1 -> ConfigValue trait from the `local` namespace since it’s no longer used in gateway-rs

Fixup config/router

---

src/service/poc_iot.proto

The reported tx_power does _not_ include the asserted gain. The verification will need to take the asserted gain into account.

Add comment for becon report tx_power

---

src/service/iot_config.proto

Adds an admin RPC to the iot_config proto allowing an admin user (signing the request messages with the authorized admin keypair) to load the contents of a `Region.res7.h3idx` file output by the lorawan-h3 `lw-generator`, as well as a collection of `blockchain_region_params_v1` into the appropriate region within the config service.

config api for loading region info into config svc

---

src/service/iot_config.proto

Renaming the messages for the gateway load region as well to conform to the convention used by the other service req/res messages

make region index file non-optional

---

.github/workflows/rust.yml
Cargo.toml
README.md
build.rs

This removes the vendored protoc dependency and rely on the host platform to have the right version installed.
The vendored protoc were added to suppport `cross` docker images that did not have the ability to add protoc to the image. This is now possible in cross.
This is an alternate solution to #272

Remove protoc dependency

---

src/blockchain_poc_core_v1.proto

This attaches `reward_unit` and `hex_scale` to the poc_witness and poc_receipt proto, so that downstream applications (ETL, explorer) can look it up.

Attach hex_scale and reward_unit to poc witness and receipts

---

src/lib.rs
src/service/iot_config.proto

split out rpcs used to manage the config service itself to group them according to function

admin api service

---

src/service/poc_mobile.proto

In order to keep the end device anonymous, remove identifying information from data session reports

Remove data identity from data transfer session

---

build-cpp.sh
build.rs
src/lib.rs
src/service/mobile_config.proto

define the initial implementation of a `mobile-config` service, the mobile subdao equivalent to the iot-config service that supplies various network configuration and metadata access to the iot subdao data oracles.
the first draft of the mobile config service provides the following three service definitions and their associated message types:
- hotspot service: retrieves individual metadata for a given hotspot, requested by the hotspot's NFT identifying pubkey binary, a successful record retrieval indicates the presence of the request hotspot on-chain. initial hotspot metadata includes the pubkey binary and the hotspot's asserted h3 location index. also includes a "list all" streaming rpc for getting all on-chain hotspots
- router service: confirm the authority of a given router to burn …

first revision of mobile config service proto

---

src/service/iot_config.proto

Sending and receiving session keys as binaries are proving to be difficult to manage on the routing side of the infrastructure. For consistency with the rest of the routing data (devaddrs, eui pairs) converting session key wire-format to a hex-encoded string

Change session key filters to hex-encoded strings

---

src/service/local.proto

Adds a `router` status local GRPC call to get the current connection status of the packet router

Add router_status rpc call

---

package.json

In order to use the service protos to decide the S3 Oracle data, they need to be published for those using npm

Add service protos to package.json

---

src/service/poc_lora.proto

Refactors the GatewayRewardShare into IotRewardShare and allows for various reward types to be supported, each with their own individual data requirements

update proto for non gateway related rewards

---

src/lib.rs
src/service/iot_config.proto
src/service/mobile_config.proto

allow management of signing keys for oracles to verify requests coming to the config server (from the verifier for instance)

config services signature/signers and metadata message types

---

src/service/poc_mobile.proto

Post-solana migration, gateways are no longer linked directly to an owner wallet (for validation purposes) so the existing `GatewayOwnerNotFound` error is no longer a valid option. This change deprecates the old invalid reason and adds a replacement for the situation where the mobile verifier cannot find the heartbeating gateway's pubkey address on the blockchain. (This is a distinct situation from the mobile gateway being _asserted_ to a location which is not something mobile poc cares about at the time of this PR)

deprecate old heartbeat invalid reason; add new correct one

---

src/service/iot_config.proto

Adds a receiver_nsid field to the http roaming protocol

add receiver_nsid to http protocol for 1.1

---

src/service/iot_config.proto

Allow for updating IoT Org records in the Config Service via RPC.
The single update request message mirrors the `org_res_v1` which includes the full list of pubkeys and devaddr constraints associated to an org record via its OUI, but the `oneof` field allows for supplying a single update at a time for simplifying the API (one request to one change) while still using the separate types within the `oneof` field for the server side to switch off of when authorizing the different types of requests based on the allowed operator (administrator vs. org self-managing)

RPC for updating org records

---

src/service/packet_verifier.proto
src/service/poc_mobile.proto

Adds support for subscriber id to data pipeline
linked oracle PR: andymck/realtime-mobile-verifier-plus-location-sharing-rewards-tmp1

subscriber id in data transfer requests and events

---

src/service/mobile_config.proto

the bulk of the "carrier" (formerly router) key validation functionality was already implemented on the `router` service and its associated messages, but we didn't have a great definition for the details of the feature at the time. b/c of that, i believe it's pretty safe to update these RPCs/messages as they haven't been utilized as of yet in the production mobile config service and we can just replace the old definitions in-place

convert router to carrier key naming; replace key type with role

---

src/service/poc_lora.proto

This field lacked a comment, which led me to believe that SNR was being recorded as integer decibels. It is not. It's fixed-point _tenths_ of a decibel, which we have been informally calling "ddB". (Even though, grrr, it's better described as centiBels, or cBm).
To confirm, this is where gateway-rs encodes the SNR into protobuf form:
https://github.com/helium/gateway-rs/blob/f224f15b93fbc140343bc99349ec32e46f1005d4/src/packet.rs#L80C5-L80C46

Add comment confirming that SNR is stored in centibels

---

src/service/mobile_config.proto

allow adding PCS (propagation calculation service) keys to the mobile config service to verify carrier PCS report signatures during mobile verification

allow adding pcs keys to mobile config

---

src/service/poc_mobile.proto

Since we defaulted this value in all of our output, we can safely remove this. Any new field will default for the output

No harm no foul, completely remove coverage objects from radio reward

---

src/service/poc_lora.proto

Adds location, gain and elevation to invalid beacon reports.  This is to compliment the inclusion of denied reports in the outputs to S3.  
Do not merge until linked PR https://github.com/helium/oracles/pull/588 is ready

include metadata fields for invalid beacons

---

src/service/poc_lora.proto

Adds an invalid_details field which can be populated with context on why a POC report was declared invalid.  The invalid_details value should be descriptive and add additional value to the denied reason.

support invalid details for invalid beacons and witnesses

---

src/service/poc_mobile.proto

In troubleshooting various issues, I realized how valuable having all the multipliers be recorded in the mobile_verifier outputs would be.

Add fields to heartbeat and mobile_reward_share files to help understand how rewards are calculated

---

build.rs
src/hex_boosting.proto
src/lib.rs
src/service/mobile_config.proto
src/service/poc_mobile.proto

oracle PR: https://github.com/helium/oracles/pull/716/files

hex boosting protos

---

src/service/poc_mobile.proto

`location_trust_score_multiplier` is said to be working for both indoor and outdoor wifi. Updating the comment accordingly

Update comment to include wifi outdoor

---

src/service/poc_mobile.proto

Unresolved questions:
- Do we attach the filename of the new datasets to the message?

Add oracle boosting report

---

src/lib.rs
src/service/poc_mobile.proto

Proposal to add radio_reward_v2 to mobile_reward_share.  The new radio_reward_v2 contains all the information that is used when determining the rewards for a radio.  For a while both radio_reward and radio_reward_v2 would be written out for each radio to have backwards compatibility.  The proposal is to add a v2 to create a clean break from the existing structure. we looked at trying to fit all the data into the existing structure but it seemed to add confusion.

Add radio-reward-v2 for mobile-reward-share

---

src/service/poc_mobile.proto

Oracles: https://github.com/helium/oracles/pull/857
- Added `data_transfer_session_req_v1.status` of enum `data_transfer_session_settlement_status`
- indicates whether a session can have it's DC burned immediately, or needs manual intervention
- Added `pending_data_transfer_session_v1` for publicly auditable pending sessions

add settlement status to data transfer session

---

src/service/poc_mobile.proto

Support new ban_type for HIP-131
https://github.com/helium/HIP/blob/main/0131-bridging-gap-between-verification-mappers-and-anti-gaming-measures.md

Update bantype in proto

---

src/service/mobile_config.proto
src/service/poc_mobile.proto

Add `DeviceType.wifi_data_only`.
Add invalid reasons for speedtests and heartbeats. Data Only hotspots are not expected submit speedtests or heartbeats.

Add Data Only device type

---

src/reward_manifest.proto
src/service/poc_mobile.proto

- do not write them to rewards manifest or mobile rewards until flow is finalized

Soft revert of service provider allocations

---

src/service/poc_mobile.proto

The difference between valid and invalid up to this point.
- Valid :: dc has been burned for the transfer event.
- Invalid :: We don't know one of the entities involced.
The invalid report will no longer be written. It is being replaced by Verified. All data transfer events that pass muster, we know the entities, it's not a duplicated, etc,. are written as Verified. Valid still means dc was burned.

add verified data transfer ingest report

---

src/lib.rs
src/reward_manifest.proto
src/service/mobile_config.proto
src/service/poc_mobile.proto
src/service_provider.proto

- Remove promotion_reward_v1 messages and reports
- Remove promotion_fund_v1 messages and reports
- Simplify promotion_reward for NFT usage
- Add endpoint to mobile-config for listing all service provider promotions
- Add Promotion Reward as MobileRewardShare type
- Write service provider promotions in mobile rewards manifest

Update Service Provider Promotions for updated flow

---

src/service/poc_mobile.proto

Adds usage count msgs to support hip 118 visualization data

hip 118 visualization data 

---

src/service/mobile_config.proto

Since changes in gateway info response (#429, #430) breaks backward compatibility (due to signing message from server side and verifying on client):
- revert (v1) changes
- make v2 version
- make v1 version deprecated

Add gateway_info_v2, gateway_info_stream_req_v2, gateway_metadata_v2

---

src/service/poc_mobile.proto

Messages for a service processing CDRs to submit unique connection counts for wifi hotspots.
- Renames `radio_reward_v2.boosted_hex_status` -> `radio_reward_v2.sp_boosted_hex_status`
- Adds `radio_reward_v2.oracle_boosted_hex_status` field

HIP-134 unique connections

---

src/service/mobile_config.proto

Related PR: https://github.com/helium/oracles/pull/910

Change `min_refreshed_at` to `min_updated_at` in `gateway_info_v2`

---

src/service/poc_mobile.proto

V2 is introduced to satisfy backward compatibility.
We have to set the 0 value as unspecified

Introduce carrier_id_v2 enum
